### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -L ba,dout,hist,livetime,msdos,nax,nd,parms,te,thex`

### CODE REVIEW

**Comment by zonca** [comment]
This is just a mirror please contribute upstream to https://heasarc.gsfc.nasa.gov/fitsio/

**Comment by luzpaz** [comment]
do they have an repo ?

**Comment by zonca** [comment]
probably not

**Comment by luzpaz** [comment]
They list this email address for bug reports: ccfits@heasarc.gsfc.nasa.gov

**Pull request closed without merging**
